name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: 25

      - name: Install dependencies
        run: npm ci

      - name: Force Failure
        run: npm run test
